server:
  port: 8087

spring:
  application:
    name: payment-service
  cloud:
    stream:
      bindings:
        paymentsRequest-in-0:
          destination: payments.request
          content-type: application/json
          group: payment-service-group
      kafka:
        binder:
          brokers: ${KAFKA_BOOTSTRAP_SERVERS:2.tcp.ngrok.io:17669}   
spring.config.import: "configserver:http://config-server:8888"