server:
  port: 8087

spring:
  application:
    name: payment-service
  cloud:
    stream:
      bindings:
        paymentsRequest-in-0:
          destination: payments.request
          content-type: application/json
          group: payment-service-group
      kafka:
        binder:
          brokers: ${KAFKA_BOOTSTRAP_SERVERS:4.tcp.ngrok.io:18305}   
spring.config.import: "optional:configserver:http://config-server:8888"
