server:
  port: 8082

spring:
  graphql:
    path: /graphql
    graphiql:
      enabled: true
      path: /graphiql
    playground:
      enabled: true
      path: /playground

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:2.tcp.ngrok.io:17669}
    consumer:
      group-id: service-catalog
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

  cloud:
    stream:
      bindings:
        serviceCreated-out-0:   
          destination: service.created
          content-type: application/json
      kafka:
        binder:
          brokers: ${KAFKA_BOOTSTRAP_SERVERS:2.tcp.ngrok.io:17669}
      defaultBinder: kafka
weather:
  api:
    key: eb5f81a5ddc6cba0c677fb69bc2f6e00

info:
  app:
    name: Service Catalog Microservice
    description: A microservice for the service catalog funcionalities
    version: 1.0.0
  company:
    name: eco-tourism-marketplace
  build:
    time: ${BUILD_TIME:2024-09-19T12:30:00Z}
