server:
  port: 8081

info:
  app:
    name: User profile Microservice
    description: A microservice for the users profile operations
    version: 1.0.0
  build:
    time: ${BUILD_TIME:2024-08-21T12:30:00Z}


spring:
  cloud:
    stream:
      bindings:
        providerCreated-out-0:
          destination: provider.created
          content-type: application/json
        userCreated-out-0:       
          destination: user.created
          content-type: application/json
      kafka:
        binder:
          brokers: ${KAFKA_BOOTSTRAP_SERVERS:4.tcp.ngrok.io:18305}
      defaultBinder: kafka
